name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1300b71114cd5f6f2366dc4a8ba4fb3b03e0aadfdbc653c0ae14130df5d3d47"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
