name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f101f26e6af407fab61f233912d21a9a3a2f0442ece86ca6cb2fbd3914c90203"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
