name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82678eb244e946269ca502e03045011de04e66cd56891e860728a01b52b1021d"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
