name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95648a930d80ed7fb2eeb2c7254096a59174191e6e96b829441510ba1c408236"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
