name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f658253c97697634701f8ff2455db763c4e1d473db8b77e3d5c8971d2f927cb1"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
