name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28298969f72c4d04f7948d253f7caf08a7b479954f56f3f285cae7533b5e8196"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
