name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "849e3491bf7de389e81f9f8aafaa047a28deecc36e1e1da4f3c6cf8d3c8023ef"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
