name = "lotech"
author = "branchpanic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0af955557188e4f6eb9b8e24afd5dad6d1b74eaaa125c96de4523e9c949db224"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
